### ISSUE TITLE
Use python related pipeline

### ISSUE THREAD

**Issue by s1mark** [dobiantal/AFP_project#19]
Try implementing the following pipeline workflow
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Comment by s1mark** [comment]
Try this first
https://github.com/actions/setup-python#basic-usage

**Comment by s1mark** [comment]
```yaml
name: 'python'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'python'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python main.py
```
